db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
app:
  image: "rocket.chat"
  command: "/bin/bash -c 'sleep 20 && node main.js'"
  environment:
    - MONGO_URL=mongodb://db:27017/meteor
    - ROOT_URL
    - MAIL_URL
  links:
    - db:db
  volumes:
    - ./logs:/home/app/logs
    - ./data/uploads:/app/uploads
web:
  image: nginx
  links:
    - app
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
